apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secret-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secret-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "secret-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "secret-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "secret-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: operator
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - kopf
          args:
            - run
            - /app/secret_operator.py
            {{- if .Values.operator.verbose }}
            - --verbose
            {{- end }}
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: WATCH_NAMESPACES
              value: {{ .Values.operator.watchNamespaces | quote }}
            - name: REFRESH_BUFFER_SECONDS
              value: "{{ .Values.operator.refreshBufferSeconds }}"
            - name: MIN_SLEEP_SECONDS
              value: "{{ .Values.operator.minSleepSeconds }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
